[theme]
base="light"
primaryColor = "#ff9999"  # Pink accent color
backgroundColor = "#f5f5f5"  # Light gray background
secondaryBackgroundColor = "#ffffff"  # White for secondary elements
textColor = "#333333"  # Dark text color
font = "sans serif" 
